# Traefik is provided by K3d by default, no need to deploy custom one
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.10.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        executor: KubernetesExecutor
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/davidm094/MLOPS_Proyecto_Final.git
            branch: main
            subPath: apps/airflow/dags
        
        # --- IMAGE CONFIGURATION (Redundant Strategy) ---
        # 1. Modern/Community Chart Structure
        images:
          airflow:
            repository: davidm094/mlops-airflow
            tag: v1
            pullPolicy: Always
        
        # 2. Legacy Chart Structure
        airflow:
          image:
            repository: davidm094/mlops-airflow
            tag: v1
            pullPolicy: Always

        # 3. Global Defaults (Very Old Charts)
        defaultAirflowRepository: davidm094/mlops-airflow
        defaultAirflowTag: v1
        # ------------------------------------------------
        
        env:
          - name: AIRFLOW_VAR_S3_ENDPOINT
            value: "http://seaweedfs-s3.mlops.svc:8333"
          - name: AWS_ACCESS_KEY_ID
            value: "any"
          - name: AWS_SECRET_ACCESS_KEY
            value: "any"
          - name: AIRFLOW__KUBERNETES__DELETE_WORKER_PODS
            value: "False"
        createUserJob:
          useHelmHooks: false
          applyCustomEnv: false
        migrateDatabaseJob:
          useHelmHooks: false
          applyCustomEnv: false
          jobAnnotations:
            "argocd.argoproj.io/hook": Sync
        postgresql:
          enabled: false
        data:
          metadataConnection:
            user: airflow
            pass: airflow
            host: postgres-postgresql.mlops.svc.cluster.local
            port: 5432
            db: airflow
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mlflow
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 0.7.13
    helm:
      valueFiles:
        - values.yaml
      values: |
        backendStore:
          postgres:
            enabled: true
            host: postgres-postgresql
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow-password
        artifactRoot:
          s3:
            enabled: true
            bucket: mlflow-artifacts
            awsAccessKeyId: any
            awsSecretAccessKey: any
            s3EndpointUrl: http://seaweedfs-s3.mlops.svc:8333
        serviceAccount:
          create: true
          name: mlflow
        extraEnvVars:
          MLFLOW_S3_ENDPOINT_URL: "http://seaweedfs-s3.mlops.svc:8333"
          AWS_DEFAULT_REGION: "us-east-1"
        service:
          type: NodePort
          port: 5000
          nodePort: 30500
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: seaweedfs
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    targetRevision: 3.59.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        s3:
          enabled: true
          port: 8333
          replication:
            enable: false
        filer:
          enabled: true
          replicas: 1
          storage:
            enabled: true
            size: 10Gi
            storageClass: "local-path"
        volume:
          enabled: true
          replicas: 1
          minFreeSpacePercent: 1
          size: 10Gi
          storageClass: "local-path"
        master:
          enabled: true
          replicas: 1
          storage:
            enabled: true
            size: 1Gi
            storageClass: "local-path"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setup-buckets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidm094/MLOPS_Proyecto_Final.git
    targetRevision: HEAD
    path: infra/manifests/setup
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.12.10
    helm:
      values: |
        auth:
          username: postgres
          password: airflow-postgres-root
          database: mlflow
        primary:
          persistence:
            enabled: true
            size: 8Gi
          storageClass: "local-path"
        initdbScripts:
          init.sql: |
            CREATE USER mlflow WITH PASSWORD 'mlflow-password';
            CREATE DATABASE mlflow OWNER mlflow;
            GRANT ALL PRIVILEGES ON DATABASE mlflow TO mlflow;
        image:
          registry: docker.io
          repository: library/postgres
          tag: 13-alpine
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidm094/MLOPS_Proyecto_Final.git
    targetRevision: HEAD
    path: apps/api/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidm094/MLOPS_Proyecto_Final.git
    targetRevision: HEAD
    path: apps/frontend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
