apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidm094/MLOPS_Proyecto_Final.git
    targetRevision: HEAD
    path: infra/manifests/metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: airflow
    repoURL: https://airflow.apache.org
    targetRevision: 1.10.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        executor: KubernetesExecutor
        dags:
          gitSync:
            enabled: true
            repo: https://github.com/davidm094/MLOPS_Proyecto_Final.git
            branch: main
            dir: apps/airflow/dags
        # Update Airflow to use SeaweedFS S3
        extraEnv:
          - name: AIRFLOW_VAR_S3_ENDPOINT
            value: http://seaweedfs-s3.mlops.svc:8333
          - name: AWS_ACCESS_KEY_ID
            value: any
          - name: AWS_SECRET_ACCESS_KEY
            value: any
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: mlflow
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 0.7.13
    helm:
      valueFiles:
        - values.yaml
      values: |
        backendStore:
          postgres:
            enabled: true
            host: postgres-postgresql
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflow-password
        artifactRoot: s3://mlflow-artifacts
        serviceAccount:
          create: true
          name: mlflow
        extraEnvVars:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://seaweedfs-s3.mlops.svc:8333
          - name: AWS_ACCESS_KEY_ID
            value: any
          - name: AWS_SECRET_ACCESS_KEY
            value: any
          - name: AWS_DEFAULT_REGION
            value: us-east-1
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: seaweedfs
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    targetRevision: 3.59.0
    helm:
      valueFiles:
        - values.yaml
      values: |
        s3:
          enabled: true
          port: 8333
          replication:
            enable: false
        filer:
          enabled: true
          replicas: 1
          storage:
            enabled: true
            size: 10Gi
            storageClass: "longhorn-single"
        volume:
          enabled: true
          replicas: 1
          minFreeSpacePercent: 1
          size: 10Gi
          storageClass: "longhorn-single"
        master:
          enabled: true
          replicas: 1
          storage:
            enabled: true
            size: 1Gi
            storageClass: "longhorn-single"
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setup-buckets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/davidm094/MLOPS_Proyecto_Final.git
    targetRevision: HEAD
    path: infra/manifests/setup
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 12.12.10
    helm:
      values: |
        auth:
          username: mlflow
          password: mlflow-password
          database: mlflow
        primary:
          persistence:
            enabled: true
            size: 8Gi
        # Fix for Bitnami image pulling: Use explicit image tag if possible or check if it works.
        # User had issues with Bitnami MinIO. Postgres might be fine or same issue.
        # Let's force a tag if needed, but 12.12.10 chart uses a specific tag.
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
